language: node_js
node_js:
    - '10'
dist: trusty
sudo: required
before_script:
    - sudo chown -R $(whoami) ~/.npm
    - npm install @angular/cli
script:
    - npm run lint
    - npm run test
    - npm run build
